db:
    image: "mongo:${MONGODB_VERSION}"
    ports:
        - "27017:27017"

app:
  build: "app/" 
  links:
    - db
  ports:
    - "9292:9292"
  environment:
    - DOCKER_ENV=true  
    - RACK_ENV=DOCKER_DEV
  command: /bin/bash start.sh
  working_dir: /app

